import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Card } from "../components/Card";
import { SearchBar } from "../components/SearchBar";
import Home1 from './Home'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Home1 />
      <SearchBar handleChange={() => {}} />
      <Card title="aaa" url="url" imageUrl="imageUrl" description="description" />
      <Card title="aaa" url="url" imageUrl="imageUrl" description="description" />
      <Card title="aaa" url="url" imageUrl="imageUrl" description="description" />
    </div>
  );
};

export default Home;
